function runAnimations() {
  document.querySelector("#id-2229").addEventListener("click", func_2229_127);

  function func_2229_127(e) {
    document.querySelector(".parent-div").classList.add("parent-animation-354");
    document.querySelector("#id-354").classList.add("animationClass-354");
    document.querySelector("#id-353").classList.add("animationClass-353");
    document.querySelector("#id-2223").classList.add("nullAnimation-2223");
    document.querySelector("#id-2233").classList.add("animationClass-null2233");
    document.querySelector("#id-2238").classList.add("animationClass-null2238");
    document.querySelector("#id-2224").classList.add("nullAnimation-2224");
    document.querySelector("#id-2229").classList.add("nullAnimation-2229");
    document.querySelector("#id-2239").classList.add("animationClass-null2239");
    document
      .querySelector("#id-2239 > div:first-child")
      .classList.add("bgClass-2239");
    document.querySelector("#id-2234").classList.add("animationClass-null2234");
    document
      .querySelector("#id-2234 > div:first-child")
      .classList.add("bgClass-2234");
    document.querySelector("#id-1051").classList.add("animationClass-null1051");
    document.querySelector("#id-2225").classList.add("nullAnimation-2225");
    document.querySelector("#id-2230").classList.add("nullAnimation-2230");
    document.querySelector("#id-2235").classList.add("animationClass-null2235");
    document
      .querySelector("#id-2235 > div:first-child")
      .classList.add("bgClass-2235");
    document.querySelector("#id-2240").classList.add("animationClass-null2240");
    document
      .querySelector("#id-2240 > div:first-child")
      .classList.add("bgClass-2240");
    document.querySelector("#id-2226").classList.add("nullAnimation-2226");
    document.querySelector("#id-2227").classList.add("nullAnimation-2227");
    document.querySelector("#id-2231").classList.add("nullAnimation-2231");
    document.querySelector("#id-2232").classList.add("nullAnimation-2232");
    document.querySelector("#id-208").classList.add("animationClass-null208");
    document.querySelector("#id-209").classList.add("animationClass-null209");
    document.querySelector("#id-2011").classList.add("animationClass-null2011");
    document.querySelector("#id-2010").classList.add("animationClass-null2010");
    document.querySelector("#id-2236").classList.add("animationClass-null2236");
    document
      .querySelector("#id-2236 > div:first-child")
      .classList.add("bgClass-2236");
    document.querySelector("#id-2237").classList.add("animationClass-null2237");
    document
      .querySelector("#id-2237 > div:first-child")
      .classList.add("bgClass-2237");
    document.querySelector("#id-2241").classList.add("animationClass-null2241");
    document
      .querySelector("#id-2241 > div:first-child")
      .classList.add("bgClass-2241");
    document.querySelector("#id-2242").classList.add("animationClass-null2242");
    document
      .querySelector("#id-2242 > div:first-child")
      .classList.add("bgClass-2242");
    document.querySelector("#id-1052").classList.add("animationClass-null1052");
    document.querySelector("#id-1085").classList.add("animationClass-null1085");
    document.querySelector("#id-1088").classList.add("animationClass-null1088");
    document.querySelector("#id-1084").classList.add("animationClass-null1084");
    document.querySelector("#id-1087").classList.add("animationClass-null1087");
    document.querySelector("#id-1053").classList.add("animationClass-null1053");
    document
      .querySelector("#id-1053 > div:first-child")
      .classList.add("bgClass-1053");
    document.querySelector("#id-1083").classList.add("animationClass-null1083");
    document.querySelector("#id-1054").classList.add("animationClass-null1054");
    document.querySelector("#id-1089").classList.add("animationClass-null1089");
    document.querySelector("#id-1090").classList.add("animationClass-null1090");
    document.querySelector("#id-1055").classList.add("animationClass-null1055");
    document.querySelector("#id-1056").classList.add("animationClass-null1056");
    document
      .querySelector("#id-1056 > div:first-child")
      .classList.add("bgClass-1056");
    document.querySelector("#id-1058").classList.add("animationClass-null1058");
    document
      .querySelector("#id-1058 > div:first-child")
      .classList.add("bgClass-1058");
    document.querySelector("#id-1057").classList.add("animationClass-null1057");
    document
      .querySelector("#id-1057 > div:first-child")
      .classList.add("bgClass-1057");
    document.querySelector("#id-1063").classList.add("animationClass-null1063");
    document.querySelector("#id-1064").classList.add("animationClass-null1064");
    document.querySelector("#id-1065").classList.add("animationClass-null1065");
    document.querySelector("#id-1079").classList.add("animationClass-null1079");
    document.querySelector("#id-1072").classList.add("animationClass-null1072");
    document.querySelector("#id-1080").classList.add("animationClass-null1080");
    document.querySelector("#id-1073").classList.add("animationClass-null1073");
    document.querySelector("#id-1074").classList.add("animationClass-null1074");
    document.querySelector("#id-1076").classList.add("animationClass-null1076");
    document.querySelector("#id-1077").classList.add("animationClass-null1077");
    document.querySelector("#id-1078").classList.add("animationClass-null1078");
    document.querySelector("#id-1221").classList.add("nullAnimation-1221");
    document.querySelector("#id-1059").classList.add("animationClass-null1059");
    document.querySelector("#id-1060").classList.add("animationClass-null1060");
    document
      .querySelector("#id-1060 > div:first-child")
      .classList.add("bgClass-1060");
    document.querySelector("#id-1061").classList.add("animationClass-null1061");
    document
      .querySelector("#id-1061 > div:first-child")
      .classList.add("bgClass-1061");
    document.querySelector("#id-1062").classList.add("animationClass-null1062");
    document
      .querySelector("#id-1062 > div:first-child")
      .classList.add("bgClass-1062");
    document.querySelector("#id-1066").classList.add("animationClass-null1066");
    document.querySelector("#id-1067").classList.add("animationClass-null1067");
    document.querySelector("#id-1069").classList.add("animationClass-null1069");
    document.querySelector("#id-1081").classList.add("animationClass-null1081");
    document.querySelector("#id-1082").classList.add("animationClass-null1082");
    document.querySelector("#id-1071").classList.add("animationClass-null1071");
    document.querySelector("#id-1075").classList.add("animationClass-null1075");
    document.querySelector("#id-1068").classList.add("animationClass-null1068");
    document.querySelector("#id-1070").classList.add("animationClass-null1070");
    document
      .querySelector("#id-2229")
      .removeEventListener("click", func_2229_127);

    setTimeout(() => {
      document
        .querySelector("#id-2240")
        .addEventListener("click", func_2240_128);
    }, 100);
  }

  function func_2240_128(e) {
    document.querySelector(".parent-div").classList.add("parent-animation-127");
    document.querySelector("#id-354").classList.add("animationClass-127");
    document.querySelector("#id-353").classList.add("nullAnimation-353");
    document.querySelector("#id-2223").classList.add("animationClass-null2223");
    document.querySelector("#id-2233").classList.add("animationClass-2233");
    document.querySelector("#id-2238").classList.add("animationClass-2238");
    document.querySelector("#id-2224").classList.add("animationClass-null2224");
    document
      .querySelector("#id-2224 > div:first-child")
      .classList.add("bgClass-2224");
    document.querySelector("#id-2229").classList.add("animationClass-null2229");
    document
      .querySelector("#id-2229 > div:first-child")
      .classList.add("bgClass-2229");
    document.querySelector("#id-2239").classList.add("animationClass-2239");
    document.querySelector("#id-2234").classList.add("animationClass-2234");
    document
      .querySelector(".bush1-1051-0")
      .classList.add("animationClass-1051-1051-0");
    document.querySelector("#id-1051").classList.add("animationClass-1051");
    document.querySelector("#id-2225").classList.add("animationClass-null2225");
    document
      .querySelector("#id-2225 > div:first-child")
      .classList.add("bgClass-2225");
    document.querySelector("#id-2230").classList.add("animationClass-null2230");
    document
      .querySelector("#id-2230 > div:first-child")
      .classList.add("bgClass-2230");
    document.querySelector("#id-2235").classList.add("animationClass-2235");
    document.querySelector("#id-2240").classList.add("animationClass-2240");
    document.querySelector("#id-2226").classList.add("animationClass-null2226");
    document
      .querySelector("#id-2226 > div:first-child")
      .classList.add("bgClass-2226");
    document.querySelector("#id-2227").classList.add("animationClass-null2227");
    document
      .querySelector("#id-2227 > div:first-child")
      .classList.add("bgClass-2227");
    document.querySelector("#id-2231").classList.add("animationClass-null2231");
    document
      .querySelector("#id-2231 > div:first-child")
      .classList.add("bgClass-2231");
    document.querySelector("#id-2232").classList.add("animationClass-null2232");
    document
      .querySelector("#id-2232 > div:first-child")
      .classList.add("bgClass-2232");
    document
      .querySelector(".home1-208-0")
      .classList.add("animationClass-208-208-0");
    document.querySelector("#id-208").classList.add("animationClass-208");
    document
      .querySelector(".about1-209-0")
      .classList.add("animationClass-209-209-0");
    document.querySelector("#id-209").classList.add("animationClass-209");
    document
      .querySelector(".course1-2011-0")
      .classList.add("animationClass-2011-2011-0");
    document.querySelector("#id-2011").classList.add("animationClass-2011");
    document
      .querySelector(".shop1-2010-0")
      .classList.add("animationClass-2010-2010-0");
    document.querySelector("#id-2010").classList.add("animationClass-2010");
    document.querySelector("#id-2236").classList.add("animationClass-2236");
    document.querySelector("#id-2237").classList.add("animationClass-2237");
    document.querySelector("#id-2241").classList.add("animationClass-2241");
    document.querySelector("#id-2242").classList.add("animationClass-2242");
    document
      .querySelector(".grow-talent-bui-1052-0")
      .classList.add("animationClass-1052-1052-0");
    document.querySelector("#id-1052").classList.add("animationClass-1052");
    document.querySelector("#id-1085").classList.add("animationClass-1085");
    document.querySelector("#id-1088").classList.add("animationClass-1088");
    document.querySelector("#id-1084").classList.add("animationClass-1084");
    document.querySelector("#id-1087").classList.add("animationClass-1087");
    document.querySelector("#id-1053").classList.add("animationClass-1053");
    document
      .querySelector("#id-1053 > div:first-child")
      .classList.add("bgClass-1215");
    document.querySelector("#id-1083").classList.add("animationClass-1083");
    document
      .querySelector(".build-skills1-1054-0")
      .classList.add("animationClass-1054-1054-0");
    document.querySelector("#id-1054").classList.add("animationClass-1054");
    document.querySelector("#id-1089").classList.add("animationClass-1089");
    document.querySelector("#id-1090").classList.add("animationClass-1090");
    document.querySelector("#id-1055").classList.add("animationClass-1055");
    document.querySelector("#id-1056").classList.add("animationClass-1056");
    document
      .querySelector("#id-1056 > div:first-child")
      .classList.add("bgClass-1218");
    document.querySelector("#id-1058").classList.add("animationClass-1058");
    document
      .querySelector("#id-1058 > div:first-child")
      .classList.add("bgClass-1220");
    document.querySelector("#id-1057").classList.add("animationClass-1057");
    document
      .querySelector("#id-1057 > div:first-child")
      .classList.add("bgClass-1219");
    document.querySelector("#id-1063").classList.add("animationClass-1063");
    document.querySelector("#id-1064").classList.add("animationClass-1064");
    document.querySelector("#id-1065").classList.add("animationClass-1065");
    document.querySelector("#id-1079").classList.add("animationClass-1079");
    document.querySelector("#id-1072").classList.add("animationClass-1072");
    document.querySelector("#id-1080").classList.add("animationClass-1080");
    document
      .querySelector(".price503-1073-0")
      .classList.add("animationClass-1073-1073-0");
    document.querySelector("#id-1073").classList.add("animationClass-1073");
    document
      .querySelector(".price504-1074-0")
      .classList.add("animationClass-1074-1074-0");
    document.querySelector("#id-1074").classList.add("animationClass-1074");
    document
      .querySelector(".price506-1076-0")
      .classList.add("animationClass-1076-1076-0");
    document.querySelector("#id-1076").classList.add("animationClass-1076");
    document
      .querySelector(".price507-1077-0")
      .classList.add("animationClass-1077-1077-0");
    document.querySelector("#id-1077").classList.add("animationClass-1077");
    document
      .querySelector(".price508-1078-0")
      .classList.add("animationClass-1078-1078-0");
    document.querySelector("#id-1078").classList.add("animationClass-1078");
    document.querySelector("#id-1221").classList.add("animationClass-null1221");
    document.querySelector("#id-1059").classList.add("animationClass-1059");
    document.querySelector("#id-1060").classList.add("animationClass-1060");
    document
      .querySelector("#id-1060 > div:first-child")
      .classList.add("bgClass-1222");
    document.querySelector("#id-1061").classList.add("animationClass-1061");
    document
      .querySelector("#id-1061 > div:first-child")
      .classList.add("bgClass-1223");
    document.querySelector("#id-1062").classList.add("animationClass-1062");
    document
      .querySelector("#id-1062 > div:first-child")
      .classList.add("bgClass-1224");
    document.querySelector("#id-1066").classList.add("animationClass-1066");
    document.querySelector("#id-1067").classList.add("animationClass-1067");
    document.querySelector("#id-1069").classList.add("animationClass-1069");
    document.querySelector("#id-1081").classList.add("animationClass-1081");
    document.querySelector("#id-1082").classList.add("animationClass-1082");
    document.querySelector("#id-1071").classList.add("animationClass-1071");
    document
      .querySelector(".price505-1075-0")
      .classList.add("animationClass-1075-1075-0");
    document.querySelector("#id-1075").classList.add("animationClass-1075");
    document
      .querySelector(".price501-1068-0")
      .classList.add("animationClass-1068-1068-0");
    document.querySelector("#id-1068").classList.add("animationClass-1068");
    document
      .querySelector(".price502-1070-0")
      .classList.add("animationClass-1070-1070-0");
    document.querySelector("#id-1070").classList.add("animationClass-1070");
    document
      .querySelector("#id-2240")
      .removeEventListener("click", func_2240_128);

    setTimeout(() => {
      document
        .querySelector("#id-2229")
        .addEventListener("click", func_2229_127);
    }, 100);
  }

  function func_2229_127(e) {
    document.querySelector(".parent-div").classList.add("parent-animation-128");
    document.querySelector("#id-354").classList.add("animationClass-128");
    document.querySelector("#id-2223").classList.add("animationClass-2223");
    document.querySelector("#id-2233").classList.add("animationClass-null2233");
    document.querySelector("#id-2238").classList.add("animationClass-null2238");
    document.querySelector("#id-2224").classList.add("animationClass-2224");
    document.querySelector("#id-2229").classList.add("animationClass-2229");
    document.querySelector("#id-2239").classList.add("animationClass-null2239");
    document
      .querySelector("#id-2239 > div:first-child")
      .classList.add("bgClass-2239");
    document.querySelector("#id-2234").classList.add("animationClass-null2234");
    document
      .querySelector("#id-2234 > div:first-child")
      .classList.add("bgClass-2234");
    document
      .querySelector(".bush1-1051-0")
      .classList.add("animationClass-1213-1213-0");
    document.querySelector("#id-1051").classList.add("animationClass-1213");
    document.querySelector("#id-2225").classList.add("animationClass-2225");
    document.querySelector("#id-2230").classList.add("animationClass-2230");
    document.querySelector("#id-2235").classList.add("animationClass-null2235");
    document
      .querySelector("#id-2235 > div:first-child")
      .classList.add("bgClass-2235");
    document.querySelector("#id-2240").classList.add("animationClass-null2240");
    document
      .querySelector("#id-2240 > div:first-child")
      .classList.add("bgClass-2240");
    document.querySelector("#id-2226").classList.add("animationClass-2226");
    document.querySelector("#id-2227").classList.add("animationClass-2227");
    document.querySelector("#id-2231").classList.add("animationClass-2231");
    document.querySelector("#id-2232").classList.add("animationClass-2232");
    document
      .querySelector(".home1-208-0")
      .classList.add("animationClass-129-129-0");
    document.querySelector("#id-208").classList.add("animationClass-129");
    document
      .querySelector(".about1-209-0")
      .classList.add("animationClass-1210-1210-0");
    document.querySelector("#id-209").classList.add("animationClass-1210");
    document
      .querySelector(".course1-2011-0")
      .classList.add("animationClass-1212-1212-0");
    document.querySelector("#id-2011").classList.add("animationClass-1212");
    document
      .querySelector(".shop1-2010-0")
      .classList.add("animationClass-1211-1211-0");
    document.querySelector("#id-2010").classList.add("animationClass-1211");
    document.querySelector("#id-2236").classList.add("animationClass-null2236");
    document
      .querySelector("#id-2236 > div:first-child")
      .classList.add("bgClass-2236");
    document.querySelector("#id-2237").classList.add("animationClass-null2237");
    document
      .querySelector("#id-2237 > div:first-child")
      .classList.add("bgClass-2237");
    document.querySelector("#id-2241").classList.add("animationClass-null2241");
    document
      .querySelector("#id-2241 > div:first-child")
      .classList.add("bgClass-2241");
    document.querySelector("#id-2242").classList.add("animationClass-null2242");
    document
      .querySelector("#id-2242 > div:first-child")
      .classList.add("bgClass-2242");
    document
      .querySelector(".grow-talent-bui-1052-0")
      .classList.add("animationClass-1214-1214-0");
    document.querySelector("#id-1052").classList.add("animationClass-1214");
    document.querySelector("#id-1085").classList.add("animationClass-1247");
    document.querySelector("#id-1088").classList.add("animationClass-1250");
    document.querySelector("#id-1084").classList.add("animationClass-1246");
    document.querySelector("#id-1087").classList.add("animationClass-1249");
    document.querySelector("#id-1053").classList.add("animationClass-1215");
    document
      .querySelector("#id-1053 > div:first-child")
      .classList.add("bgClass-1053");
    document.querySelector("#id-1083").classList.add("animationClass-1245");
    document
      .querySelector(".build-skills1-1054-0")
      .classList.add("animationClass-1216-1216-0");
    document.querySelector("#id-1054").classList.add("animationClass-1216");
    document.querySelector("#id-1089").classList.add("animationClass-1251");
    document.querySelector("#id-1090").classList.add("animationClass-1252");
    document.querySelector("#id-1055").classList.add("animationClass-1217");
    document.querySelector("#id-1056").classList.add("animationClass-1218");
    document
      .querySelector("#id-1056 > div:first-child")
      .classList.add("bgClass-1056");
    document.querySelector("#id-1058").classList.add("animationClass-1220");
    document
      .querySelector("#id-1058 > div:first-child")
      .classList.add("bgClass-1058");
    document.querySelector("#id-1057").classList.add("animationClass-1219");
    document
      .querySelector("#id-1057 > div:first-child")
      .classList.add("bgClass-1057");
    document.querySelector("#id-1063").classList.add("animationClass-1225");
    document.querySelector("#id-1064").classList.add("animationClass-1226");
    document.querySelector("#id-1065").classList.add("animationClass-1227");
    document.querySelector("#id-1079").classList.add("animationClass-1241");
    document.querySelector("#id-1072").classList.add("animationClass-1234");
    document.querySelector("#id-1080").classList.add("animationClass-1242");
    document
      .querySelector(".price503-1073-0")
      .classList.add("animationClass-1235-1235-0");
    document.querySelector("#id-1073").classList.add("animationClass-1235");
    document
      .querySelector(".price504-1074-0")
      .classList.add("animationClass-1236-1236-0");
    document.querySelector("#id-1074").classList.add("animationClass-1236");
    document
      .querySelector(".price506-1076-0")
      .classList.add("animationClass-1238-1238-0");
    document.querySelector("#id-1076").classList.add("animationClass-1238");
    document
      .querySelector(".price507-1077-0")
      .classList.add("animationClass-1239-1239-0");
    document.querySelector("#id-1077").classList.add("animationClass-1239");
    document
      .querySelector(".price508-1078-0")
      .classList.add("animationClass-1240-1240-0");
    document.querySelector("#id-1078").classList.add("animationClass-1240");
    document.querySelector("#id-1221").classList.add("animationClass-1221");
    document.querySelector("#id-1059").classList.add("nullAnimation-1059");
    document.querySelector("#id-1060").classList.add("animationClass-1222");
    document
      .querySelector("#id-1060 > div:first-child")
      .classList.add("bgClass-1060");
    document.querySelector("#id-1061").classList.add("animationClass-1223");
    document
      .querySelector("#id-1061 > div:first-child")
      .classList.add("bgClass-1061");
    document.querySelector("#id-1062").classList.add("animationClass-1224");
    document
      .querySelector("#id-1062 > div:first-child")
      .classList.add("bgClass-1062");
    document.querySelector("#id-1066").classList.add("animationClass-1228");
    document.querySelector("#id-1067").classList.add("animationClass-1229");
    document.querySelector("#id-1069").classList.add("animationClass-1231");
    document.querySelector("#id-1081").classList.add("animationClass-1243");
    document.querySelector("#id-1082").classList.add("animationClass-1244");
    document.querySelector("#id-1071").classList.add("animationClass-1233");
    document
      .querySelector(".price505-1075-0")
      .classList.add("animationClass-1237-1237-0");
    document.querySelector("#id-1075").classList.add("animationClass-1237");
    document
      .querySelector(".price501-1068-0")
      .classList.add("animationClass-1230-1230-0");
    document.querySelector("#id-1068").classList.add("animationClass-1230");
    document
      .querySelector(".price502-1070-0")
      .classList.add("animationClass-1232-1232-0");
    document.querySelector("#id-1070").classList.add("animationClass-1232");
    document
      .querySelector("#id-2229")
      .removeEventListener("click", func_2229_127);

    setTimeout(() => {
      //loop login
      document
        .querySelector(".parent-div")
        .classList.remove("parent-animation-354");
      document.querySelector("#id-354").classList.remove("animationClass-354");
      document.querySelector("#id-353").classList.remove("animationClass-353");
      document.querySelector("#id-2223").classList.remove("nullAnimation-2223");
      document
        .querySelector("#id-2233")
        .classList.remove("animationClass-null2233");
      document
        .querySelector("#id-2238")
        .classList.remove("animationClass-null2238");
      document.querySelector("#id-2224").classList.remove("nullAnimation-2224");
      document.querySelector("#id-2229").classList.remove("nullAnimation-2229");
      document
        .querySelector("#id-2239")
        .classList.remove("animationClass-null2239");
      document
        .querySelector("#id-2239 > div:first-child")
        .classList.remove("bgClass-2239");
      document
        .querySelector("#id-2234")
        .classList.remove("animationClass-null2234");
      document
        .querySelector("#id-2234 > div:first-child")
        .classList.remove("bgClass-2234");
      document
        .querySelector("#id-1051")
        .classList.remove("animationClass-null1051");
      document.querySelector("#id-2225").classList.remove("nullAnimation-2225");
      document.querySelector("#id-2230").classList.remove("nullAnimation-2230");
      document
        .querySelector("#id-2235")
        .classList.remove("animationClass-null2235");
      document
        .querySelector("#id-2235 > div:first-child")
        .classList.remove("bgClass-2235");
      document
        .querySelector("#id-2240")
        .classList.remove("animationClass-null2240");
      document
        .querySelector("#id-2240 > div:first-child")
        .classList.remove("bgClass-2240");
      document.querySelector("#id-2226").classList.remove("nullAnimation-2226");
      document.querySelector("#id-2227").classList.remove("nullAnimation-2227");
      document.querySelector("#id-2231").classList.remove("nullAnimation-2231");
      document.querySelector("#id-2232").classList.remove("nullAnimation-2232");
      document
        .querySelector("#id-208")
        .classList.remove("animationClass-null208");
      document
        .querySelector("#id-209")
        .classList.remove("animationClass-null209");
      document
        .querySelector("#id-2011")
        .classList.remove("animationClass-null2011");
      document
        .querySelector("#id-2010")
        .classList.remove("animationClass-null2010");
      document
        .querySelector("#id-2236")
        .classList.remove("animationClass-null2236");
      document
        .querySelector("#id-2236 > div:first-child")
        .classList.remove("bgClass-2236");
      document
        .querySelector("#id-2237")
        .classList.remove("animationClass-null2237");
      document
        .querySelector("#id-2237 > div:first-child")
        .classList.remove("bgClass-2237");
      document
        .querySelector("#id-2241")
        .classList.remove("animationClass-null2241");
      document
        .querySelector("#id-2241 > div:first-child")
        .classList.remove("bgClass-2241");
      document
        .querySelector("#id-2242")
        .classList.remove("animationClass-null2242");
      document
        .querySelector("#id-2242 > div:first-child")
        .classList.remove("bgClass-2242");
      document
        .querySelector("#id-1052")
        .classList.remove("animationClass-null1052");
      document
        .querySelector("#id-1085")
        .classList.remove("animationClass-null1085");
      document
        .querySelector("#id-1088")
        .classList.remove("animationClass-null1088");
      document
        .querySelector("#id-1084")
        .classList.remove("animationClass-null1084");
      document
        .querySelector("#id-1087")
        .classList.remove("animationClass-null1087");
      document
        .querySelector("#id-1053")
        .classList.remove("animationClass-null1053");
      document
        .querySelector("#id-1053 > div:first-child")
        .classList.remove("bgClass-1053");
      document
        .querySelector("#id-1083")
        .classList.remove("animationClass-null1083");
      document
        .querySelector("#id-1054")
        .classList.remove("animationClass-null1054");
      document
        .querySelector("#id-1089")
        .classList.remove("animationClass-null1089");
      document
        .querySelector("#id-1090")
        .classList.remove("animationClass-null1090");
      document
        .querySelector("#id-1055")
        .classList.remove("animationClass-null1055");
      document
        .querySelector("#id-1056")
        .classList.remove("animationClass-null1056");
      document
        .querySelector("#id-1056 > div:first-child")
        .classList.remove("bgClass-1056");
      document
        .querySelector("#id-1058")
        .classList.remove("animationClass-null1058");
      document
        .querySelector("#id-1058 > div:first-child")
        .classList.remove("bgClass-1058");
      document
        .querySelector("#id-1057")
        .classList.remove("animationClass-null1057");
      document
        .querySelector("#id-1057 > div:first-child")
        .classList.remove("bgClass-1057");
      document
        .querySelector("#id-1063")
        .classList.remove("animationClass-null1063");
      document
        .querySelector("#id-1064")
        .classList.remove("animationClass-null1064");
      document
        .querySelector("#id-1065")
        .classList.remove("animationClass-null1065");
      document
        .querySelector("#id-1079")
        .classList.remove("animationClass-null1079");
      document
        .querySelector("#id-1072")
        .classList.remove("animationClass-null1072");
      document
        .querySelector("#id-1080")
        .classList.remove("animationClass-null1080");
      document
        .querySelector("#id-1073")
        .classList.remove("animationClass-null1073");
      document
        .querySelector("#id-1074")
        .classList.remove("animationClass-null1074");
      document
        .querySelector("#id-1076")
        .classList.remove("animationClass-null1076");
      document
        .querySelector("#id-1077")
        .classList.remove("animationClass-null1077");
      document
        .querySelector("#id-1078")
        .classList.remove("animationClass-null1078");
      document.querySelector("#id-1221").classList.remove("nullAnimation-1221");
      document
        .querySelector("#id-1059")
        .classList.remove("animationClass-null1059");
      document
        .querySelector("#id-1060")
        .classList.remove("animationClass-null1060");
      document
        .querySelector("#id-1060 > div:first-child")
        .classList.remove("bgClass-1060");
      document
        .querySelector("#id-1061")
        .classList.remove("animationClass-null1061");
      document
        .querySelector("#id-1061 > div:first-child")
        .classList.remove("bgClass-1061");
      document
        .querySelector("#id-1062")
        .classList.remove("animationClass-null1062");
      document
        .querySelector("#id-1062 > div:first-child")
        .classList.remove("bgClass-1062");
      document
        .querySelector("#id-1066")
        .classList.remove("animationClass-null1066");
      document
        .querySelector("#id-1067")
        .classList.remove("animationClass-null1067");
      document
        .querySelector("#id-1069")
        .classList.remove("animationClass-null1069");
      document
        .querySelector("#id-1081")
        .classList.remove("animationClass-null1081");
      document
        .querySelector("#id-1082")
        .classList.remove("animationClass-null1082");
      document
        .querySelector("#id-1071")
        .classList.remove("animationClass-null1071");
      document
        .querySelector("#id-1075")
        .classList.remove("animationClass-null1075");
      document
        .querySelector("#id-1068")
        .classList.remove("animationClass-null1068");
      document
        .querySelector("#id-1070")
        .classList.remove("animationClass-null1070");
      document
        .querySelector(".parent-div")
        .classList.remove("parent-animation-127");
      document.querySelector("#id-354").classList.remove("animationClass-127");
      document.querySelector("#id-353").classList.remove("nullAnimation-353");
      document
        .querySelector("#id-2223")
        .classList.remove("animationClass-null2223");
      document
        .querySelector("#id-2233")
        .classList.remove("animationClass-2233");
      document
        .querySelector("#id-2238")
        .classList.remove("animationClass-2238");
      document
        .querySelector("#id-2224")
        .classList.remove("animationClass-null2224");
      document
        .querySelector("#id-2224 > div:first-child")
        .classList.remove("bgClass-2224");
      document
        .querySelector("#id-2229")
        .classList.remove("animationClass-null2229");
      document
        .querySelector("#id-2229 > div:first-child")
        .classList.remove("bgClass-2229");
      document
        .querySelector("#id-2239")
        .classList.remove("animationClass-2239");
      document
        .querySelector("#id-2234")
        .classList.remove("animationClass-2234");
      document
        .querySelector(".bush1-1051-0")
        .classList.remove("animationClass-1051-1051-0");
      document
        .querySelector("#id-1051")
        .classList.remove("animationClass-1051");
      document
        .querySelector("#id-2225")
        .classList.remove("animationClass-null2225");
      document
        .querySelector("#id-2225 > div:first-child")
        .classList.remove("bgClass-2225");
      document
        .querySelector("#id-2230")
        .classList.remove("animationClass-null2230");
      document
        .querySelector("#id-2230 > div:first-child")
        .classList.remove("bgClass-2230");
      document
        .querySelector("#id-2235")
        .classList.remove("animationClass-2235");
      document
        .querySelector("#id-2240")
        .classList.remove("animationClass-2240");
      document
        .querySelector("#id-2226")
        .classList.remove("animationClass-null2226");
      document
        .querySelector("#id-2226 > div:first-child")
        .classList.remove("bgClass-2226");
      document
        .querySelector("#id-2227")
        .classList.remove("animationClass-null2227");
      document
        .querySelector("#id-2227 > div:first-child")
        .classList.remove("bgClass-2227");
      document
        .querySelector("#id-2231")
        .classList.remove("animationClass-null2231");
      document
        .querySelector("#id-2231 > div:first-child")
        .classList.remove("bgClass-2231");
      document
        .querySelector("#id-2232")
        .classList.remove("animationClass-null2232");
      document
        .querySelector("#id-2232 > div:first-child")
        .classList.remove("bgClass-2232");
      document
        .querySelector(".home1-208-0")
        .classList.remove("animationClass-208-208-0");
      document.querySelector("#id-208").classList.remove("animationClass-208");
      document
        .querySelector(".about1-209-0")
        .classList.remove("animationClass-209-209-0");
      document.querySelector("#id-209").classList.remove("animationClass-209");
      document
        .querySelector(".course1-2011-0")
        .classList.remove("animationClass-2011-2011-0");
      document
        .querySelector("#id-2011")
        .classList.remove("animationClass-2011");
      document
        .querySelector(".shop1-2010-0")
        .classList.remove("animationClass-2010-2010-0");
      document
        .querySelector("#id-2010")
        .classList.remove("animationClass-2010");
      document
        .querySelector("#id-2236")
        .classList.remove("animationClass-2236");
      document
        .querySelector("#id-2237")
        .classList.remove("animationClass-2237");
      document
        .querySelector("#id-2241")
        .classList.remove("animationClass-2241");
      document
        .querySelector("#id-2242")
        .classList.remove("animationClass-2242");
      document
        .querySelector(".grow-talent-bui-1052-0")
        .classList.remove("animationClass-1052-1052-0");
      document
        .querySelector("#id-1052")
        .classList.remove("animationClass-1052");
      document
        .querySelector("#id-1085")
        .classList.remove("animationClass-1085");
      document
        .querySelector("#id-1088")
        .classList.remove("animationClass-1088");
      document
        .querySelector("#id-1084")
        .classList.remove("animationClass-1084");
      document
        .querySelector("#id-1087")
        .classList.remove("animationClass-1087");
      document
        .querySelector("#id-1053")
        .classList.remove("animationClass-1053");
      document
        .querySelector("#id-1053 > div:first-child")
        .classList.remove("bgClass-1215");
      document
        .querySelector("#id-1083")
        .classList.remove("animationClass-1083");
      document
        .querySelector(".build-skills1-1054-0")
        .classList.remove("animationClass-1054-1054-0");
      document
        .querySelector("#id-1054")
        .classList.remove("animationClass-1054");
      document
        .querySelector("#id-1089")
        .classList.remove("animationClass-1089");
      document
        .querySelector("#id-1090")
        .classList.remove("animationClass-1090");
      document
        .querySelector("#id-1055")
        .classList.remove("animationClass-1055");
      document
        .querySelector("#id-1056")
        .classList.remove("animationClass-1056");
      document
        .querySelector("#id-1056 > div:first-child")
        .classList.remove("bgClass-1218");
      document
        .querySelector("#id-1058")
        .classList.remove("animationClass-1058");
      document
        .querySelector("#id-1058 > div:first-child")
        .classList.remove("bgClass-1220");
      document
        .querySelector("#id-1057")
        .classList.remove("animationClass-1057");
      document
        .querySelector("#id-1057 > div:first-child")
        .classList.remove("bgClass-1219");
      document
        .querySelector("#id-1063")
        .classList.remove("animationClass-1063");
      document
        .querySelector("#id-1064")
        .classList.remove("animationClass-1064");
      document
        .querySelector("#id-1065")
        .classList.remove("animationClass-1065");
      document
        .querySelector("#id-1079")
        .classList.remove("animationClass-1079");
      document
        .querySelector("#id-1072")
        .classList.remove("animationClass-1072");
      document
        .querySelector("#id-1080")
        .classList.remove("animationClass-1080");
      document
        .querySelector(".price503-1073-0")
        .classList.remove("animationClass-1073-1073-0");
      document
        .querySelector("#id-1073")
        .classList.remove("animationClass-1073");
      document
        .querySelector(".price504-1074-0")
        .classList.remove("animationClass-1074-1074-0");
      document
        .querySelector("#id-1074")
        .classList.remove("animationClass-1074");
      document
        .querySelector(".price506-1076-0")
        .classList.remove("animationClass-1076-1076-0");
      document
        .querySelector("#id-1076")
        .classList.remove("animationClass-1076");
      document
        .querySelector(".price507-1077-0")
        .classList.remove("animationClass-1077-1077-0");
      document
        .querySelector("#id-1077")
        .classList.remove("animationClass-1077");
      document
        .querySelector(".price508-1078-0")
        .classList.remove("animationClass-1078-1078-0");
      document
        .querySelector("#id-1078")
        .classList.remove("animationClass-1078");
      document
        .querySelector("#id-1221")
        .classList.remove("animationClass-null1221");
      document
        .querySelector("#id-1059")
        .classList.remove("animationClass-1059");
      document
        .querySelector("#id-1060")
        .classList.remove("animationClass-1060");
      document
        .querySelector("#id-1060 > div:first-child")
        .classList.remove("bgClass-1222");
      document
        .querySelector("#id-1061")
        .classList.remove("animationClass-1061");
      document
        .querySelector("#id-1061 > div:first-child")
        .classList.remove("bgClass-1223");
      document
        .querySelector("#id-1062")
        .classList.remove("animationClass-1062");
      document
        .querySelector("#id-1062 > div:first-child")
        .classList.remove("bgClass-1224");
      document
        .querySelector("#id-1066")
        .classList.remove("animationClass-1066");
      document
        .querySelector("#id-1067")
        .classList.remove("animationClass-1067");
      document
        .querySelector("#id-1069")
        .classList.remove("animationClass-1069");
      document
        .querySelector("#id-1081")
        .classList.remove("animationClass-1081");
      document
        .querySelector("#id-1082")
        .classList.remove("animationClass-1082");
      document
        .querySelector("#id-1071")
        .classList.remove("animationClass-1071");
      document
        .querySelector(".price505-1075-0")
        .classList.remove("animationClass-1075-1075-0");
      document
        .querySelector("#id-1075")
        .classList.remove("animationClass-1075");
      document
        .querySelector(".price501-1068-0")
        .classList.remove("animationClass-1068-1068-0");
      document
        .querySelector("#id-1068")
        .classList.remove("animationClass-1068");
      document
        .querySelector(".price502-1070-0")
        .classList.remove("animationClass-1070-1070-0");
      document
        .querySelector("#id-1070")
        .classList.remove("animationClass-1070");
      document
        .querySelector(".parent-div")
        .classList.remove("parent-animation-128");
      document.querySelector("#id-354").classList.remove("animationClass-128");
      document
        .querySelector("#id-2223")
        .classList.remove("animationClass-2223");
      document
        .querySelector("#id-2233")
        .classList.remove("animationClass-null2233");
      document
        .querySelector("#id-2238")
        .classList.remove("animationClass-null2238");
      document
        .querySelector("#id-2224")
        .classList.remove("animationClass-2224");
      document
        .querySelector("#id-2229")
        .classList.remove("animationClass-2229");
      document
        .querySelector("#id-2239")
        .classList.remove("animationClass-null2239");
      document
        .querySelector("#id-2239 > div:first-child")
        .classList.remove("bgClass-2239");
      document
        .querySelector("#id-2234")
        .classList.remove("animationClass-null2234");
      document
        .querySelector("#id-2234 > div:first-child")
        .classList.remove("bgClass-2234");
      document
        .querySelector(".bush1-1051-0")
        .classList.remove("animationClass-1213-1213-0");
      document
        .querySelector("#id-1051")
        .classList.remove("animationClass-1213");
      document
        .querySelector("#id-2225")
        .classList.remove("animationClass-2225");
      document
        .querySelector("#id-2230")
        .classList.remove("animationClass-2230");
      document
        .querySelector("#id-2235")
        .classList.remove("animationClass-null2235");
      document
        .querySelector("#id-2235 > div:first-child")
        .classList.remove("bgClass-2235");
      document
        .querySelector("#id-2240")
        .classList.remove("animationClass-null2240");
      document
        .querySelector("#id-2240 > div:first-child")
        .classList.remove("bgClass-2240");
      document
        .querySelector("#id-2226")
        .classList.remove("animationClass-2226");
      document
        .querySelector("#id-2227")
        .classList.remove("animationClass-2227");
      document
        .querySelector("#id-2231")
        .classList.remove("animationClass-2231");
      document
        .querySelector("#id-2232")
        .classList.remove("animationClass-2232");
      document
        .querySelector(".home1-208-0")
        .classList.remove("animationClass-129-129-0");
      document.querySelector("#id-208").classList.remove("animationClass-129");
      document
        .querySelector(".about1-209-0")
        .classList.remove("animationClass-1210-1210-0");
      document.querySelector("#id-209").classList.remove("animationClass-1210");
      document
        .querySelector(".course1-2011-0")
        .classList.remove("animationClass-1212-1212-0");
      document
        .querySelector("#id-2011")
        .classList.remove("animationClass-1212");
      document
        .querySelector(".shop1-2010-0")
        .classList.remove("animationClass-1211-1211-0");
      document
        .querySelector("#id-2010")
        .classList.remove("animationClass-1211");
      document
        .querySelector("#id-2236")
        .classList.remove("animationClass-null2236");
      document
        .querySelector("#id-2236 > div:first-child")
        .classList.remove("bgClass-2236");
      document
        .querySelector("#id-2237")
        .classList.remove("animationClass-null2237");
      document
        .querySelector("#id-2237 > div:first-child")
        .classList.remove("bgClass-2237");
      document
        .querySelector("#id-2241")
        .classList.remove("animationClass-null2241");
      document
        .querySelector("#id-2241 > div:first-child")
        .classList.remove("bgClass-2241");
      document
        .querySelector("#id-2242")
        .classList.remove("animationClass-null2242");
      document
        .querySelector("#id-2242 > div:first-child")
        .classList.remove("bgClass-2242");
      document
        .querySelector(".grow-talent-bui-1052-0")
        .classList.remove("animationClass-1214-1214-0");
      document
        .querySelector("#id-1052")
        .classList.remove("animationClass-1214");
      document
        .querySelector("#id-1085")
        .classList.remove("animationClass-1247");
      document
        .querySelector("#id-1088")
        .classList.remove("animationClass-1250");
      document
        .querySelector("#id-1084")
        .classList.remove("animationClass-1246");
      document
        .querySelector("#id-1087")
        .classList.remove("animationClass-1249");
      document
        .querySelector("#id-1053")
        .classList.remove("animationClass-1215");
      document
        .querySelector("#id-1053 > div:first-child")
        .classList.remove("bgClass-1053");
      document
        .querySelector("#id-1083")
        .classList.remove("animationClass-1245");
      document
        .querySelector(".build-skills1-1054-0")
        .classList.remove("animationClass-1216-1216-0");
      document
        .querySelector("#id-1054")
        .classList.remove("animationClass-1216");
      document
        .querySelector("#id-1089")
        .classList.remove("animationClass-1251");
      document
        .querySelector("#id-1090")
        .classList.remove("animationClass-1252");
      document
        .querySelector("#id-1055")
        .classList.remove("animationClass-1217");
      document
        .querySelector("#id-1056")
        .classList.remove("animationClass-1218");
      document
        .querySelector("#id-1056 > div:first-child")
        .classList.remove("bgClass-1056");
      document
        .querySelector("#id-1058")
        .classList.remove("animationClass-1220");
      document
        .querySelector("#id-1058 > div:first-child")
        .classList.remove("bgClass-1058");
      document
        .querySelector("#id-1057")
        .classList.remove("animationClass-1219");
      document
        .querySelector("#id-1057 > div:first-child")
        .classList.remove("bgClass-1057");
      document
        .querySelector("#id-1063")
        .classList.remove("animationClass-1225");
      document
        .querySelector("#id-1064")
        .classList.remove("animationClass-1226");
      document
        .querySelector("#id-1065")
        .classList.remove("animationClass-1227");
      document
        .querySelector("#id-1079")
        .classList.remove("animationClass-1241");
      document
        .querySelector("#id-1072")
        .classList.remove("animationClass-1234");
      document
        .querySelector("#id-1080")
        .classList.remove("animationClass-1242");
      document
        .querySelector(".price503-1073-0")
        .classList.remove("animationClass-1235-1235-0");
      document
        .querySelector("#id-1073")
        .classList.remove("animationClass-1235");
      document
        .querySelector(".price504-1074-0")
        .classList.remove("animationClass-1236-1236-0");
      document
        .querySelector("#id-1074")
        .classList.remove("animationClass-1236");
      document
        .querySelector(".price506-1076-0")
        .classList.remove("animationClass-1238-1238-0");
      document
        .querySelector("#id-1076")
        .classList.remove("animationClass-1238");
      document
        .querySelector(".price507-1077-0")
        .classList.remove("animationClass-1239-1239-0");
      document
        .querySelector("#id-1077")
        .classList.remove("animationClass-1239");
      document
        .querySelector(".price508-1078-0")
        .classList.remove("animationClass-1240-1240-0");
      document
        .querySelector("#id-1078")
        .classList.remove("animationClass-1240");
      document
        .querySelector("#id-1221")
        .classList.remove("animationClass-1221");
      document.querySelector("#id-1059").classList.remove("nullAnimation-1059");
      document
        .querySelector("#id-1060")
        .classList.remove("animationClass-1222");
      document
        .querySelector("#id-1060 > div:first-child")
        .classList.remove("bgClass-1060");
      document
        .querySelector("#id-1061")
        .classList.remove("animationClass-1223");
      document
        .querySelector("#id-1061 > div:first-child")
        .classList.remove("bgClass-1061");
      document
        .querySelector("#id-1062")
        .classList.remove("animationClass-1224");
      document
        .querySelector("#id-1062 > div:first-child")
        .classList.remove("bgClass-1062");
      document
        .querySelector("#id-1066")
        .classList.remove("animationClass-1228");
      document
        .querySelector("#id-1067")
        .classList.remove("animationClass-1229");
      document
        .querySelector("#id-1069")
        .classList.remove("animationClass-1231");
      document
        .querySelector("#id-1081")
        .classList.remove("animationClass-1243");
      document
        .querySelector("#id-1082")
        .classList.remove("animationClass-1244");
      document
        .querySelector("#id-1071")
        .classList.remove("animationClass-1233");
      document
        .querySelector(".price505-1075-0")
        .classList.remove("animationClass-1237-1237-0");
      document
        .querySelector("#id-1075")
        .classList.remove("animationClass-1237");
      document
        .querySelector(".price501-1068-0")
        .classList.remove("animationClass-1230-1230-0");
      document
        .querySelector("#id-1068")
        .classList.remove("animationClass-1230");
      document
        .querySelector(".price502-1070-0")
        .classList.remove("animationClass-1232-1232-0");
      document
        .querySelector("#id-1070")
        .classList.remove("animationClass-1232");
      runAnimations();
    }, 300);
  }
}
runAnimations();
